"""Initial migration.

Revision ID: 6a4295545b84
Revises: 
Create Date: 2024-03-16 23:56:44.718150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4295545b84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botuser',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('bot_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('repeat_interval', sa.Enum('everyday', 'every_week', 'every_month', 'every_year', name='repeatinterval'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_reminded', sa.Boolean),
    sa.ForeignKeyConstraint(['bot_user_id'], ['botuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    op.drop_table('botuser')
    # ### end Alembic commands ###
