"""Update is_reminded. Delete repeat interval.

Revision ID: 9080a8a4fb60
Revises: 6a4295545b84
Create Date: 2024-03-17 18:30:01.976811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9080a8a4fb60"
down_revision: Union[str, None] = "6a4295545b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reminder", "is_reminded", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("reminder", "repeat_interval")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column(
            "repeat_interval",
            postgresql.ENUM(
                "everyday",
                "every_week",
                "every_month",
                "every_year",
                name="repeatinterval",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "reminder", "is_reminded", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
